- name: Backend setup
  hosts: all
  become: yes
  vars:
    db_name: "expense_db"
    db_user: "root"
    db_password: "ExpenseApp@1"
    db_host: "mysql-dev.pdops.shop"
    app_user: "expense"
    app_dir: "/app"
    backend_service_file: "backend.service"
    s3_url: "https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip"

  tasks:
    - name: Disable default Node.js module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add application user
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Clean old app content
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: absent

    - name: Recreate app directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: "{{ s3_url }}"
        dest: "{{ app_dir }}"
        remote_src: yes

    - name: Install Node.js dependencies
      community.general.npm:
        path: "{{ app_dir }}"
        state: latest

    - name: Copy backend service file
      ansible.builtin.copy:
        src: "{{ backend_service_file }}"
        dest: /etc/systemd/system/backend.service

    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: Load schema into MySQL
      community.mysql.mysql_db:
        state: import
        name: "{{ db_name }}"
        target: "{{ app_dir }}/schema/backend.sql"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"

    - name: Start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon_reload: yes