- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: disable default NodeJS Version Module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS module for V20
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        - name: nodejs
          state: installed

    - name: Adding Application User
      ansible.builtin.user:
        name: expense

    - name: Clean old app content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Recreate app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download NodeJS Dependencies
      community.general.npm:
        path: /app
        state: latest


    - name: Copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install MySQL Client
      ansible.builtin.dnf: msql
      sate: installed

    - name: load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.pdops.shop

    - name: start backed service
      ansible.builtin.system_service:
        name: backend
        state: restarted
        enabled: yes
        demon_reload: yes












#
#    Print_Task_Heading "Install MySQL Client"
#    dnf install mysql -y &>>$LOG
#    Check_Status $?
#
#    Print_Task_Heading "Load Schema"
#    mysql -h mysql-dev.rdevops6a.online -uroot -p${mysql_root_password} < /app/schema/backend.sql &>>$LOG
#    Check_Status $?