- name: Frontend setup
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
         name: nginx
         state: latest

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
         state: started
         name: nginx

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
