- name: Front setup
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:  # Use 'yum' for older RHEL-based systems
        name: nginx
        state: latest

    - name: Enable and start nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes  # Ensures nginx starts on boot

