- name: MySQL Setup
  hosts: all
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Start and Enable MySQL
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Wait for MySQL to be ready
      ansible.builtin.wait_for:
        port: 3306
        delay: 5
        timeout: 30

    - name: Set MySQL root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: ExpenseApp@1
        login_user: root
        login_password: ExpenseApp@1
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
        state: present
